name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - name: My first step - check out repository
        uses: actions/checkout@v4
      # this step uses runs node actions and install bun script
      - name: install node and bun 
      - uses: actions/setup-node@v4
      - uses: oven-sh/setup-bun@v1
        with:
          node-version: '20'
          bun-version: 'latest'
      - run: bun install -g bats
      - run: bats -v
      - run: bun -v
